### ISSUE TITLE
Cannot install anything 

### ISSUE THREAD

**Issue by mrusli70** [host505/repository.host505#10]
I managed to download the file but it cannot seems to download anything to install the repo??? Keep getting dependency problem. Any work around to get around???

**Comment by host505** [comment]
If you updated kodi from 18.x to 19.x, that's your problem, you need a clean 19 installation.
If not, gonna need more details, what did you dl and try to install?

**Comment by mrusli70** [comment]
Sorry for the late reply, Install Kodi 19.1 fresh install. Windows 10, Windows 11, Manjaro. MacOS. All from fresh install. Cannot download repo to be install having script dependency error. No Python scripts to be install. Try so many times, nothing works. Even log in to VPN still cannot install repos.
