### ISSUE TITLE
Script dependancy error cannot install repo. 

### ISSUE THREAD

**Issue by mrusli70** [host505/repository.host505#11]
Here is the screenshots and I cannot install any repos. See the screenshot for the logs errors. I really do not know what had happen. I try on MacOS, Windows, Linux all are the same errors. I think the server is down. 

![Screenshot 2021-09-09 at 1 11 41 PM](https://user-images.githubusercontent.com/64156595/132626806-c596a791-2010-48a8-b608-7782a92fa7cd.png)
![Screenshot 2021-09-09 at 1 11 55 PM](https://user-images.githubusercontent.com/64156595/132626822-f79b216f-221a-4a0e-aac5-32be19574b2a.png)
![Screenshot 2021-09-09 at 1 12 04 PM](https://user-images.githubusercontent.com/64156595/132626830-d0a2f993-70d6-439f-9481-5a81c36712bb.png)
![Screenshot 2021-09-09 at 1 12 22 PM](https://user-images.githubusercontent.com/64156595/132626838-52cde5bf-46b9-447f-a3db-1656eb2e4e7f.png)
![Screenshot 2021-09-09 at 1 13 22 PM](https://user-images.githubusercontent.com/64156595/132626846-241024fa-b89d-4eb2-82ca-fd6afc0418ba.png)

**Comment by host505** [comment]
Repo contents and ALL dependencies are hosted here, on GitHub, so server definitely isn't down lol
And it was just yesterday that I performed an installation - no issues.
I see you also have issues installing other add-ons, didn't it crossed your mind that there must be something wrong with your virtual os's?
Can't/won't debug such configuration, sorry.
