### ISSUE TITLE
python update  3.10 -Kodi crash

### ISSUE THREAD

**Issue by holzboa** [host505/repository.host505#14]
A new python package release was just pushed to Arch stable going from version 3.9 to 3.10.

After that update Kodi crashes with theoath installed.
After removing script.modules from ~/.kodi/addons/ Kodi starts fine.

**Comment by mmetak** [comment]
[FS#73004 - [kodi] crash since python 3.10.1](https://bugs.archlinux.org/task/73004)
[FS#73002 - [python] broken subinterpreters](https://bugs.archlinux.org/task/73002)

**Comment by host505** [comment]
So I guess nothing to do with the add-on.
