### ISSUE TITLE
oathscrapers module addon.xml version missmatch

### ISSUE THREAD

**Issue by kolekan** [host505/repository.host505#15]
Last version of OS is 1.03.01. 
In addon.xml inside zip file version is 1.03.00a that causing dependency failed of theoath last version.

**Comment by i300220** [comment]
idem,
rolled back to 1.03.00 temporarily.

**Comment by host505** [comment]
@kolekan thanks for spotting the issue. Should be fixed now.

**Comment by kolekan** [comment]
Yes it is fixed in 1.03.02.
