### ISSUE TITLE
NO free streams with the LAW & Order , multiple series and spinoffs.

### ISSUE THREAD

**Issue by eeden003** [host505/repository.host505#17]
Dear Sirs. Offcourse is The Oath my goto addon, day after day, for a very long time, great free links, frequently updates and great information concerning the changes. However, the addon has since a very very long time problems with finding free links with hte series ; Law and Order: organized Crime, Law and Order SVU, and now also with the new season of Law and Order(original series0, 0, ZERO free links. Why ? All other series have multiple working free links. So, I have to make use of the addon Sealteam6 with free links. Why can find that other addon links and your great addon not ? I have this problems on Kodi19, and 2 boxes with Kodi18, and on my PC. The Resolvers, yes, I still have2 resolvers, are uptodate and all other addons work but most addons cannot find Law and Order.  Maybe Sealteam6 use a site or a way to find the Law and Order series that is unknow to you ? Please advice. Thanks very much and greetings from The Netherlands.

**Comment by host505** [comment]
It's the `&` in the title. I replace `&` with `and` (among other title cleanup) before I send the title to the scrapers.
The reason I do it is to match 'scene' releases titles on torrent/premium links sites do so too.
Sites with free links tend to keep the `&`.
I had to make a decision at some point and, debrid wins, sorry.

**Comment by eeden003** [comment]
Thanks for your clear and fast explanation ! It makes sence, and YOU are the "boss", not I.   I'm  99,9 percent happy with your addon and the great working free links, so I will make use of other ways to find my Law and Order series. Keep up the good work and stay healthty. Jan.
