### ISSUE TITLE
Trakt sync/library update notification

### ISSUE THREAD

**Issue by bw905** [host505/repository.host505#18]
Hi Host505, 

Wondering if there is a way to hide the notification popup for the "Auto syncing trakt library" message? On a large collection it can remain visible for several minutes and is not hidden by the player. Ive tried simply editing line 128 of libtools.py to be:
`        self.silentDialog = True`
with no results. I do admit I am a total n00b just trying to figure things out. 

Looks to me the actual call for this notification is at lines 338 to 344 of libtools.py (again Im just guessing)

```
def silent(self, url):
        control.idle()

        if not control.condVisibility('Window.IsVisible(infodialog)') and not control.condVisibility('Player.HasVideo'):
            control.infoDialog(control.lang(32608), time=10000000)
            self.infoDialog = True
            self.silentDialog = True

```
Any advice or thoughts on how to hide this notification, possibly using the userdata settings.xml?

**Comment by host505** [comment]
I guess you could adjust the time that the info dialog is visible [here](https://github.com/host505/plugin.video.theoath/blob/master/resources/lib/modules/libtools.py#L177) and [here](https://github.com/host505/plugin.video.theoath/blob/master/resources/lib/modules/libtools.py#L342).
Change the `time` param - unit is milliseconds.
But perhaps you'll lose the `Sync Complete` info dialog if the process takes longer than what you'll set there.

**Comment by bw905** [comment]
Thanks, I will give it shot.
