### ISSUE TITLE
EasyNews integration - enhancement

### ISSUE THREAD

**Issue by Turd001234** [host505/repository.host505#2]
can you please add easynews into the oathscrapers module's scraper accounts section. thanks for reading and considering.

**Comment by host505** [comment]
Does the openscrapers one work? If yes I'll port it to oathscrapers.
But I'm gonna make a test build for you to test, as I don't have an easynews sub.
In a couple of days though, too busy porting to tmdb rn.

**Comment by Turd001234** [comment]
sorry for the delay. 
yes, it does work when authenticated in accounts and easynews is enabled in hosters (disabled by default) i do find that it freezes scraping process for a chunk of time, but it does eventually produce a list of links. not sure if it's a small bug or not.
