### ISSUE TITLE
Matrix  Version TheOath -  Flatten Seasons and Play From Here

### ISSUE THREAD

**Issue by rogermae** [host505/repository.host505#6]
I am unable to binge watch my shows in this addon. I like that it gives me more links than Seren or Fen. 

In my context menu the Play From Here button is missing. I have autoplay enabled and Resume Playback is on by default. Also there is no option to flatten seasons in the main menu. These were available in the Leia version however.

**Comment by host505** [comment]
Flatten feature was removed upon the change from tvdb to TMDb as metadata provider for shows - it's not coming back.
Play from here, indeed does not appear under kodi 19 (it still does under older kodi versions) - will be fixed on next update.

**Comment by host505** [comment]
v.4.00.24 should fix Play from here not appearing on k19.
Thanks for bringing it to my attention, never noticed it as I don't use it.
