### ISSUE TITLE
Trakt updates

### ISSUE THREAD

**Issue by Sobersally** [host505/repository.host505#8]
I love the Oath! However, I find that my trakt is not updating in The Oath.  Is there something that I should be doing to sync it after watching some episodes?

Thanks!
Sober

**Comment by host505** [comment]
What doesn't update, the watched status?
Did you try re-authorising?

**Comment by jewbmx** [comment]
Might need to check the script.trakt addon settings and maybe make sure the settings dont conflict with TheOath settings
